import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Escape-Bridge",
  description: "Generated by create next app",
};

const neonClub = localFont({
  src: "./fonts/neon-club-music.bold.otf",
  variable: "--font-neon-club",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${neonClub.variable}`}>
        {children}
      </body>
    </html>
  );
}
